/* Generated by the Systemtap dtrace wrapper */

#define _SDT_HAS_SEMAPHORES 1


#define STAP_HAS_SEMAPHORES 1 /* deprecated */


#include <sys/sdt.h>

/* TRACE_SAIO_PLANNING_START () */
#if defined STAP_SDT_V1
#define TRACE_SAIO_PLANNING_START_ENABLED() __builtin_expect (planning_start_semaphore, 0)
#define saio_planning_start_semaphore planning_start_semaphore
#else
#define TRACE_SAIO_PLANNING_START_ENABLED() __builtin_expect (saio_planning_start_semaphore, 0)
#endif
__extension__ extern unsigned short saio_planning_start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_SAIO_PLANNING_START() \
DTRACE_PROBE(saio,planning_start)

/* TRACE_SAIO_PLANNING_DONE () */
#if defined STAP_SDT_V1
#define TRACE_SAIO_PLANNING_DONE_ENABLED() __builtin_expect (planning_done_semaphore, 0)
#define saio_planning_done_semaphore planning_done_semaphore
#else
#define TRACE_SAIO_PLANNING_DONE_ENABLED() __builtin_expect (saio_planning_done_semaphore, 0)
#endif
__extension__ extern unsigned short saio_planning_done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_SAIO_PLANNING_DONE() \
DTRACE_PROBE(saio,planning_done)

/* TRACE_SAIO_STEP_DONE ( int, int, int, int, int) */
#if defined STAP_SDT_V1
#define TRACE_SAIO_STEP_DONE_ENABLED() __builtin_expect (step_done_semaphore, 0)
#define saio_step_done_semaphore step_done_semaphore
#else
#define TRACE_SAIO_STEP_DONE_ENABLED() __builtin_expect (saio_step_done_semaphore, 0)
#endif
__extension__ extern unsigned short saio_step_done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TRACE_SAIO_STEP_DONE(arg1,arg2,arg3,arg4,arg5) \
DTRACE_PROBE5(saio,step_done,arg1,arg2,arg3,arg4,arg5)

